export enum ButtonDataTestId {
  My_Stakes_Stake_Now = 'button:my-stakes-stake-now',
  Home_Primary = 'button:home-primary',
  Home_Secondary = 'button:home-secondary',
  Not_Found_Return_Home = 'button:not-found-return-home',
  Copy_Public_Key_To_Clipboard = 'button:copy-public-key-to-clipboard',
  Node_Card_View = 'button:node-card-view',
  Node_Card_Register = 'button:node-card-register',
  Faucet_Continue = 'button:faucet-continue',
  Faucet_Submit = 'button:faucet-submit',
  Faucet_Disconnect = 'button:faucet-disconnect',
  Dropdown_Hamburger_Menu = 'button:dropdown-hamburger-menu',
  Stake_Submit = 'button:stake-submit',
  Register_Submit_Solo = 'button:register-submit-solo',
  Register_Submit_Solo_Retry = 'button:register-submit-solo-retry',
  Register_Submit_Multi_Retry = 'button:register-submit-multi-retry',
  Stake_Submit_Retry = 'button:stake-submit-retry',
  Register_Add_Reserved = 'button:register-add-reserved',
  Register_Submit_Multi = 'button:register-submit-multi',
  Stake_Submit_Multi = 'button:stake-submit-multi',
  Register_Submit_Multi_Register_Only = 'button:register-submit-multi-register-only',
  Learn_More_Open_Nodes = 'button:learn-more-open-nodes',
  Agree_TOS = 'button:agree-tos',
  Claim_Tokens_Open_Dialog = 'button:claim-tokens-open-dialog',
  Claim_Tokens_Submit = 'button:claim-tokens-submit',
  Hide_Prepared_Registration = 'button:hide-prepared-registration',
  Staked_Node_Request_Exit = 'button:staked-node-request-exit',
  Staked_Node_Exit = 'button:staked-node-exit',
  Staked_Node_Request_Exit_Dialog_Submit = 'button:staked-node-request-exit-dialog-submit',
  Staked_Node_Request_Exit_Dialog_Cancel = 'button:staked-node-request-exit-dialog-cancel',
  Staked_Node_Request_Exit_Write_Dialog_Submit = 'button:staked-node-request-exit-write-dialog-submit',
  Staked_Node_Exit_Dialog_Submit = 'button:staked-node-exit-dialog-submit',
  Staked_Node_Copy_Staked_Balance = 'button:staked-node-copy-staked-balance',
  Staked_Node_Error_Retry = 'button:staked-node-error-retry',
  My_Stakes_Error_Retry = 'button:my-stakes-error-retry',
  Open_Nodes_Error_Retry = 'button:open-nodes-error-retry',
  Claim_Tokens_Error_Retry = 'button:claim-tokens-error-retry',
  Network_Fee_Copy_Formula = 'button:network-fee-copy-formula',
  Exit_Node_Error_Retry = 'button:exit-node-error-retry',
  Staked_Node_Start = 'button:staked-node-start',
  Maintenance_Discord = 'button:maintenance-discord',
  Maintenance_X = 'button:maintenance-x',
  Stake_Amount_Min = 'button:stake-amount-min',
  Stake_Amount_Max = 'button:stake-amount-max',
  Show_Referral_Link = 'button:show-referral-link',
  Copy_Referral_Link = 'button:copy-referral-link',
  Toggle_Show_Toaster_History = 'button:toggle-show-toaster-history',
  Registration_Back_Button = 'button:registration-back-button',
  Registration_Start_Description_External_Link = 'button:registration-start-description-external-link',
  Registration_Start_Button_Solo = 'button:registration-start-button-solo',
  Registration_Start_Button_Multi = 'button:registration-start-button-multi',
  Registration_Stake_Amount_Description_External_Link = 'button:registration-stake-amount-description-external-link',
  Registration_Stake_Amount_Min = 'button:registration-stake-amount-min',
  Registration_Stake_Amount_Max = 'button:registration-stake-amount-max',
  Registration_Stake_Amount_Slider_0 = 'button:registration-stake-amount-slider-0',
  Registration_Stake_Amount_Slider_25 = 'button:registration-stake-amount-slider-25',
  Registration_Stake_Amount_Slider_50 = 'button:registration-stake-amount-slider-50',
  Registration_Stake_Amount_Slider_75 = 'button:registration-stake-amount-slider-75',
  Registration_Stake_Amount_Slider_100 = 'button:registration-stake-amount-slider-100',
  Registration_Stake_Amount_Slider_Min = 'button:registration-stake-amount-slider-min',
  Registration_Stake_Amount_Slider_Max = 'button:registration-stake-amount-slider-max',
  Registration_Reserved_Stake_Amount_Min = 'button:registration_reserved_stake-amount-min',
  Registration_Reserved_Stake_Amount_Max = 'button:registration_reserved_stake-amount-max',
  Registration_Reserved_Stake_Amount_Slider_0 = 'button:registration_reserved_stake-amount-slider-0',
  Registration_Reserved_Stake_Amount_Slider_25 = 'button:registration_reserved_stake-amount-slider-25',
  Registration_Reserved_Stake_Amount_Slider_50 = 'button:registration_reserved_stake-amount-slider-50',
  Registration_Reserved_Stake_Amount_Slider_75 = 'button:registration_reserved_stake-amount-slider-75',
  Registration_Reserved_Stake_Amount_Slider_100 = 'button:registration_reserved_stake-amount-slider-100',
  Registration_Reserved_Stake_Amount_Slider_Min = 'button:registration_reserved_stake-amount-slider-min',
  Registration_Reserved_Stake_Amount_Slider_Max = 'button:registration_reserved_stake-amount-slider-max',
  Registration_Reserved_Stakes_Confirm = 'button:registration-reserved-stakes-confirm',
  Registration_Reserved_Stakes_Add_Slot = 'button:registration-reserved-stakes-add-slot',
  Registration_Reserved_Stakes_Confirm_Slot = 'button:registration-reserved-stakes-confirm-slot',
  Registration_Reserved_Stakes_Cancel_Slot = 'button:registration-reserved-stakes-cancel-slot',
  Registration_Stake_Amount_Continue = 'button:registration-stake-amount-continue',
  Registration_Operator_Fee_Description_External_Link = 'button:registration-operator-fee-description-external-link',
  Registration_Operator_Fee_Continue = 'button:registration-operator-fee-continue',
  Registration_Rewards_Address_Description_External_Link = 'button:registration-rewards-address-description-external-link',
  Registration_Rewards_Address_Same = 'button:registration-rewards-address-same',
  Registration_Rewards_Address_Different = 'button:registration-rewards-address-different',
  Registration_Rewards_Address_Input_Solo_Description_External_Link = 'button:registration-rewards-address-input-solo-description-external-link',
  Registration_Rewards_Address_Input_Solo_Confirm = 'button:registration-rewards-address-input-solo-confirm',
  Registration_Rewards_Address_Input_Multi_Description_External_Link = 'button:registration-rewards-address-input-multi-description-external-link',
  Registration_Rewards_Address_Input_Multi_Confirm = 'button:registration-rewards-address-input-multi-confirm',
  Registration_Reserve_Slots_Description_External_Link = 'button:registration-reserve-slots-description-external-link',
  Registration_Reserve_Slots_Skip = 'button:registration-reserve-slots-skip',
  Registration_Reserve_Slots_Reserve = 'button:registration-reserve-slots-reserve',
  Registration_Reserve_Slots_Input_Description_External_Link = 'button:registration-reserve-slots-input-description-external-link',
  Registration_Auto_Activate_Description_External_Link = 'button:registration-auto-activate-description-external-link',
  Registration_Auto_Activate_Automatic = 'button:registration-auto-activate-automatic',
  Registration_Auto_Activate_Manual = 'button:registration-auto-activate-manual',
  Registration_Submit_Multi_Confirm = 'button:registration-submit-multi-confirm',
  Registration_Submit_Solo_Confirm = 'button:registration-submit-solo-confirm',
  Registration_Submit_Solo_Edit_Rewards_Address = 'button:registration-submit-solo-edit-rewards-address',
  Registration_Submit_Multi_Edit_Rewards_Address = 'button:registration-submit-multi-edit-rewards-address',
  Registration_Submit_Multi_Edit_Stake_Amount = 'button:registration-submit-multi-edit-stake-amount',
  Registration_Submit_Multi_Edit_Operator_Fee = 'button:registration-submit-multi-edit-operator-fee',
  Registration_Submit_Multi_Edit_Reserve_Slots = 'button:registration-submit-multi-edit-reserve-slots',
  Registration_Submit_Multi_Edit_Auto_Activate = 'button:registration-submit-multi-edit-auto-activate',
  Registration_Success_Solo_View_My_Stakes = 'button:registration-success-solo-view-my-stakes',
  Registration_Success_Multi_View_My_Stakes = 'button:registration-success-multi-view-my-stakes',
  Registration_Error_Copy_To_Clipboard = 'button:registration-error-copy-to-clipboard',
  Reserved_Stakes_Table_Edit_Row = 'button:reserve-stakes-table-edit-row',
  Reserved_Stakes_Table_Remove_Row = 'button:reserve-stakes-table-remove-row',
  Stake_Submit_Confirm = 'button:stake-submit-confirm',
  Stake_Edit_Auto_Activate = 'button:stake-edit-auto-activate',
  Stake_Edit_Operator_Fee = 'button:stake-edit-operator-fee',
  Stake_Edit_Rewards_Address = 'button:stake-edit-rewards-address',
  Stake_Edit_Stake_Amount = 'button:stake-edit-stake-amount',
  Stake_New_Stake_Stake_Amount_Min = 'button:stake-new-stake-stake-amount-min',
  Stake_New_Stake_Stake_Amount_Max = 'button:stake-new-stake-stake-amount-max',
  Stake_New_Stake_Stake_Amount_Slider_0 = 'button:stake-new-stake-stake-amount-slider-0',
  Stake_New_Stake_Stake_Amount_Slider_25 = 'button:stake-new-stake-stake-amount-slider-25',
  Stake_New_Stake_Stake_Amount_Slider_50 = 'button:stake-new-stake-stake-amount-slider-50',
  Stake_New_Stake_Stake_Amount_Slider_75 = 'button:stake-new-stake-stake-amount-slider-75',
  Stake_New_Stake_Stake_Amount_Slider_100 = 'button:stake-new-stake-stake-amount-slider-100',
  Stake_New_Stake_Stake_Amount_Slider_Min = 'button:stake-new-stake-stake-amount-slider-min',
  Stake_New_Stake_Stake_Amount_Slider_Max = 'button:stake-new-stake-stake-amount-slider-max',
  Stake_New_Stake_Edit_Stake_Amount = 'button:stake-new-stake-edit-stake-amount',
  Stake_New_Stake_Edit_Rewards_Address = 'button:stake-new-stake-edit-rewards-address',
  Stake_Manage_Stake_Stake_Amount_Min = 'button:stake-manage-stake-stake-amount-min',
  Stake_Manage_Stake_Stake_Amount_Max = 'button:stake-manage-stake-stake-amount-max',
  Stake_Manage_Stake_Stake_Amount_Slider_0 = 'button:stake-manage-stake-stake-amount-slider-0',
  Stake_Manage_Stake_Stake_Amount_Slider_25 = 'button:stake-manage-stake-stake-amount-slider-25',
  Stake_Manage_Stake_Stake_Amount_Slider_50 = 'button:stake-manage-stake-stake-amount-slider-50',
  Stake_Manage_Stake_Stake_Amount_Slider_75 = 'button:stake-manage-stake-stake-amount-slider-75',
  Stake_Manage_Stake_Stake_Amount_Slider_100 = 'button:stake-manage-stake-stake-amount-slider-100',
  Stake_Manage_Stake_Stake_Amount_Slider_Min = 'button:stake-manage-stake-stake-amount-slider-min',
  Stake_Manage_Stake_Stake_Amount_Slider_Max = 'button:stake-manage-stake-stake-amount-slider-max',
  Stake_Manage_Stake_Edit_Stake_Amount = 'button:stake-manage-stake-edit-stake-amount',
  Stake_Manage_Stake_Edit_Rewards_Address = 'button:stake-manage-stake-edit-rewards-address',
  Stake_Manage_Remove_Stake = 'button:stake-manage-remove-stake',
  Vesting_Start_Continue = 'button:vesting-start-continue',
  Vesting_Start_Skip = 'button:vesting-start-skip',
  Vesting_Info_Switch = 'button:vesting-info-switch',
  Vesting_Disconnect = 'button:vesting-disconnect',
  Vesting_Wallet_Button = 'button:vesting-wallet-button',
  Vesting_Transfer_Beneficiary_Submit = 'button:vesting-transfer-beneficiary-submit',
  Vesting_Transfer_Beneficiary_Confirm = 'button:vesting-transfer-beneficiary-confirm',
  Vesting_Info_Edit_Beneficiary = 'button:vesting-info-edit-beneficiary',
  Vesting_Claim_Principal_Open_Dialog = 'button:vesting-claim-principal-open-dialog',
  Vesting_Claim_Principal_Confirm = 'button:vesting-claim-principal-confirm',
  Registration_Notice_Continue = 'button:registration-notice-continue',
  Stake_Notice_Continue = 'button:stake-notice-continue',
  Stake_Notice_Cancel = 'button:stake-notice-cancel',
  Unstake_Operator_Notice_Continue = 'button:unstake-operator-notice-continue',
  Token_Uniswap_Pool_Eth = 'button:token-uniswap-pool-eth',
  Token_Uniswap_Pool_Arb = 'button:token-uniswap-pool-arb',
}

export enum InputDataTestId {
  Registration_Rewards_Address_Solo = 'input:registration-rewards-address-solo',
  Registration_Rewards_Address_Multi = 'input:registration-rewards-address-multi',
  Registration_Stake_Amount = 'input:registration-stake-amount',
  Registration_Operator_Fee = 'input:registration-operator-fee',
  Registration_Reserved_Stake_Amount = 'input:registration-reserved-stake-amount',
  Registration_Reserved_Stake_Address = 'input:registration-reserved-stake-address',
  Stake_New_Stake_Stake_Amount = 'input:stake-new-stake-stake-amount',
  Stake_New_Stake_Rewards_Address = 'input:stake-new-stake-rewards-address',
  Stake_Manage_Stake_Stake_Amount = 'input:stake-manage-stake-stake-amount',
  Stake_Manage_Stake_Rewards_Address = 'input:stake-manage-stake-rewards-address',
  Beneficiary_Transfer_Beneficiary_Address = 'input:beneficiary-transfer-beneficiary-address',
}

export enum SwitchDataTestId {
  Vesting_Switch = 'switch:vesting-switch',
}

export enum RadioDataTestId {
  Registration_Start_Radio_Express = 'radio:registration-start-radio-express',
  Registration_Start_Radio_Guided = 'radio:registration-start-radio-guided',
}

export enum CheckboxDataTestId {
  Notice_Registration_Dont_Show_Again = 'checkbox:registration-start-radio-dont-show-again',
  Notice_Staking_Dont_Show_Again = 'checkbox:registration-start-radio-dont-show-again',
}

export enum SpecialDataTestId {
  Mainnet_Link = 'special:mainnet-link',
}

export enum ModuleDataTestId {
  Balance = 'module:balance',
  Claim_Tokens = 'module:claim-tokens',
  Unclaimed_Tokens = 'module:unclaimed-tokens',
  Daily_Rewards = 'module:daily-rewards',
}

export enum NodeCardDataTestId {
  Staked_Node = 'node-card:staked-node',
  Open_Node_Card = 'node-card:open-node-card',
}

export enum StakedNodeDataTestId {
  Indicator = 'staked-node-card:staked-node-indicator',
  Title = 'staked-node-card:staked-node-title',
  Notification = 'staked-node-card:staked-node-notification',
  Contributor_List = 'staked-node-card:staked-node-contributor-list',
  Expand_Button = 'staked-node-card:staked-node-expand-button',
  Collapse_Button = 'staked-node-card:staked-node-collapse-button',
  Pub_Key = 'staked-node-card:staked-node-pub-key',
}

export enum OpenNodeDataTestId {
  Open_Node_Card_Header = 'staked-node-card:staked-node-header',
  Open_Node_Card_Title = 'open-node-card:open-node-card-title',
  Open_Node_Card_Text = 'open-node-card:open-node-card-text',
  Open_Node_Card_Pub_Key = 'open-node-card:open-node-card-pub-key',
}

export enum NavigationDataTestId {
  Token_Uniswap_Pool_Eth = 'nav:token-uniswap-pool-eth',
  Token_Uniswap_Pool_Arb = 'nav:token-uniswap-pool-arb',
}
