export enum ButtonDataTestId {
  My_Stakes_Stake_Now = 'button:my-stakes-stake-now',
  Home_Primary = 'button:home-primary',
  Home_Primary_Mobile = 'button:home-primary-mobile',
  Home_Secondary = 'button:home-secondary',
  Home_Secondary_Mobile = 'button:home-secondary-mobile',
  Not_Found_Return_Home = 'button:not-found-return-home',
  Copy_Public_Key_To_Clipboard = 'button:copy-public-key-to-clipboard',
  Node_Card_View = 'button:node-card-view',
  Node_Card_Register = 'button:node-card-register',
  Faucet_Continue = 'button:faucet-continue',
  Faucet_Submit = 'button:faucet-submit',
  Faucet_Disconnect = 'button:faucet-disconnect',
  Dropdown_Hamburger_Menu = 'button:dropdown-hamburger-menu',
  Stake_Submit = 'button:stake-submit',
  Register_Submit_Solo = 'button:register-submit-solo',
  Register_Add_Reserved = 'button:register-add-reserved',
  Register_Submit_Multi = 'button:register-submit-multi',
  Stake_Submit_Multi = 'button:stake-submit-multi',
  Register_Submit_Multi_Register_Only = 'button:register-submit-multi-register-only',
  Learn_More_Open_Nodes = 'button:learn-more-open-nodes',
  Agree_TOS = 'button:agree-tos',
  Claim_Tokens_Open_Dialog = 'button:claim-tokens-open-dialog',
  Claim_Tokens_Submit = 'button:claim-tokens-submit',
  Hide_Prepared_Registration = 'button:hide-prepared-registration',
  Staked_Node_Request_Exit = 'button:staked-node-request-exit',
  Staked_Node_Exit = 'button:staked-node-exit',
  Staked_Node_Request_Exit_Dialog_Submit = 'button:staked-node-request-exit-dialog-submit',
  Staked_Node_Request_Exit_Dialog_Cancel = 'button:staked-node-request-exit-dialog-cancel',
  Staked_Node_Request_Exit_Write_Dialog_Submit = 'button:staked-node-request-exit-write-dialog-submit',
  Staked_Node_Exit_Dialog_Submit = 'button:staked-node-exit-dialog-submit',
  Stake_Amount_Min = 'button:stake-amount-min',
  Stake_Amount_Max = 'button:stake-amount-max',
  Finalise_Node = 'button:finalise-node',
  Show_Referral_Link = 'button:show-referral-link',
  Copy_Referral_Link = 'button:copy-referral-link',
}

export enum LinkDataTestId {
  Home_Primary = 'link:landing-primary',
  Home_Primary_Mobile = 'link:landing-primary-mobile',
  Home_Secondary = 'link:landing-secondary',
  Home_Secondary_Mobile = 'link:landing-secondary-mobile',
  Header_Nav_Link_Item = 'link:header-nav-link-item',
  Hamburger_Dropdown_Item = 'link:hamburger-dropdown-item',
  Claim_Disabled = 'link:claim-disabled',
  Node_Setup_Docs = 'link:node-setup-docs',
  Not_Found_Return_Home = 'link:not-found-return-home',
  No_Nodes_Stake_Now = 'link:no-nodes-stake-now',
  No_Nodes_Stake_Now_In_Text = 'link:no-nodes-stake-now-in-text',
  Faucet_Explorer_Transaction = 'link:faucet-explorer-transaction',
  I18n_Discord_Server = 'link:i18n-discord-server',
  I18n_Contact_Support = 'link:i18n-contact-support',
  I18n_Incentive_Program = 'link:i18n-incentive-program',
  I18n_Gas_Faucet = 'link:i18n-gas-faucet',
  I18n_Gas_Info = 'link:i18n-gas-info',
  I18n_Oxen_Program = 'link:i18n-oxen-program',
  I18n_Session_Token_Community_Snapshot = 'link:i18n-session-token-community-snapshot',
  I18n_My_Stakes = 'link:i18n-my-stakes',
  Claim_Fee_Tooltip = 'link:claim-fee-tooltip',
  Daily_Node_Reward_Tooltip = 'link:daily-node-reward-tooltip',
  Paragraph_Testnet_Referral = 'link:paragraph-testnet-referral',
  Paragraph_Testnet_Referral_ToS = 'link:paragraph-testnet-referral-tos',
  Testnet_Points_Tooltip = 'link:testnet-points-tooltip',
  Unclaimed_Tokens_Tooltip = 'link:unclaimed-tokens-tooltip',
  Registration_No_Wallet_Setup_Docs = 'link:register-no-wallet-setup-docs',
  Registration_No_Nodes_Setup_Docs = 'link:register-no-nodes-setup-docs',
  Multi_Node_Explorer_Address = 'link:multi-node-explorer-address',
  Open_No_Nodes_Setup_Docs = 'link:open-no-nodes-setup-docs',
  Fee_Gas_Info_Tooltip = 'link:fee-gas-info-tooltip',
  Request_Exit_Liquidation_Learn_More = 'link:request-exit-liquidation-learn-more',
  Exit_Timer_Liquidation_Learn_More = 'link:exit-timer-liquidation-learn-more',
  Total_Rewards_Tooltip = 'link:total-rewards-tooltip',
}

export enum SpecialDataTestId {
  Unsupported_Chain_Link = 'special:unsupported-chain-link',
  Mainnet_Not_Live_Link = 'special:mainnet-not-online-live',
}

export enum ModuleDataTestId {
  Balance = 'module:balance',
  Claim_Tokens = 'module:claim-tokens',
  Unclaimed_Tokens = 'module:unclaimed-tokens',
  Daily_Rewards = 'module:daily-rewards',
}

export enum NodeCardDataTestId {
  Staked_Node = 'node-card:staked-node',
  Open_Node_Card = 'node-card:open-node-card',
}

export enum StakedNodeDataTestId {
  Indicator = 'staked-node-card:staked-node-indicator',
  Title = 'staked-node-card:staked-node-title',
  Notification = 'staked-node-card:staked-node-notification',
  Contributor_List = 'staked-node-card:staked-node-contributor-list',
  Expand_Button = 'staked-node-card:staked-node-expand-button',
  Collapse_Button = 'staked-node-card:staked-node-collapse-button',
  Pub_Key = 'staked-node-card:staked-node-pub-key',
}

export enum OpenNodeDataTestId {
  Open_Node_Card_Header = 'staked-node-card:staked-node-header',
  Open_Node_Card_Title = 'open-node-card:open-node-card-title',
  Open_Node_Card_Text = 'open-node-card:open-node-card-text',
  Open_Node_Card_Pub_Key = 'open-node-card:open-node-card-pub-key',
}
